I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 7, in script call
    call begin_main
  File "game/screen_ch0.rpy", line 174, in script call
    call op2
  File "game/screen_op2.rpy", line 319, in script call
    call op3
  File "game/screen_op3.rpy", line 155, in script
    scene bg op3_51
Exception: Image 'bg' does not accept attributes 'op3_51'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 7, in script call
    call begin_main
  File "game/screen_ch0.rpy", line 174, in script call
    call op2
  File "game/screen_op2.rpy", line 319, in script call
    call op3
  File "game/screen_op3.rpy", line 155, in script
    scene bg op3_51
  File "E:\renpy-8.1.1-sdk\renpy\ast.py", line 1562, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "E:\renpy-8.1.1-sdk\renpy\ast.py", line 1391, in show_imspec
    renpy.config.show(name,
  File "E:\renpy-8.1.1-sdk\renpy\exports.py", line 733, in show
    if not base.find_target() and renpy.config.missing_show:
  File "E:\renpy-8.1.1-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "E:\renpy-8.1.1-sdk\renpy\display\core.py", line 496, in _duplicate
    args.extraneous()
  File "E:\renpy-8.1.1-sdk\renpy\display\core.py", line 359, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'bg' does not accept attributes 'op3_51'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.1.23060707
Sprites 1.0
Sat Dec  9 23:07:13 2023
